name: dependabot-changeset

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  changesets:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v5
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: pnpm

      - run: pnpm i --frozen-lockfile

      - name: Create changeset
        run: node scripts/dependabot-changeset.mjs

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: add changeset for dependabot'
          file_pattern: '.changeset/*.md'
